runtime: python
env: flex
entrypoint: gunicorn -b :$PORT daru_ru_ru_social_network.wsgi

beta_settings:
    cloud_sql_instances: cloud-rgr-262011:europe-west6:cloud-rgr-db


runtime_config:
  python_version: 3
  