# Generated by Django 2.2.1 on 2019-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0002_auto_20190512_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_type',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='alliance',
            new_name='game_alliance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='guild',
            new_name='game_guild',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='race',
            new_name='game_server',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='information',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='server',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='character_equip_calculator',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='game_race',
            field=models.CharField(choices=[('NN', 'None'), ('NU', 'Nuian'), ('EL', 'Elf'), ('DW', 'Dwarf'), ('FR', 'Firran'), ('HR', 'Narani'), ('WB', 'Warborn')], default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
