# Generated by Django 2.2.1 on 2019-05-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0003_auto_20190519_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='game_server',
            field=models.CharField(choices=[('NON', 'None'), ('LCS', 'Lucius'), ('ARI', 'Aria'), ('SHD', 'Shaeda'), ('KLE', 'Kaile'), ('NUI', 'Nui'), ('HZE', 'Haze'), ('KRV', 'Korvus'), ('FNM', 'Fanem')], default='NON', max_length=3),
        ),
    ]
