# Generated by Django 2.2.1 on 2019-05-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0004_auto_20190519_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallpaper',
        ),
    ]
