# Generated by Django 2.2.1 on 2019-05-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0005_remove_profile_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
