# Generated by Django 2.2.1 on 2019-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0006_auto_20190520_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
