# Generated by Django 2.2.1 on 2019-05-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0013_group_groupfeedfile_grouppost_grouppostcomment_grouppostcommentlike_grouppostlike_groupsubscriber_po'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupFeedFile',
            new_name='GroupPostFeedFile',
        ),
        migrations.RenameModel(
            old_name='PostFeedFile',
            new_name='UserPostFeedFile',
        ),
    ]
